#!/bin/sh
where=`basename $PWD`
if test "$where" != "sixjobs"
then
  echo "You must be in sixjobs to execute this update!!!"
  exit 1
fi

set -x
proversion="wbnlaug10pro"
# Get everything
# But leave out bin for the moment (just links)
for mydir in control_files inc mask plot/inc scripts utilities
do
  cp ~mcintosh/$proversion/sixjobs/$mydir/* ./$mydir
done
rm -f README
ln -s scripts/README README

cd scripts
./domyseds
cd ..
# and do ONLY the scripts for the moment
exit 0

# and now try and handle sixdeskenv and sysenv
# sixdeskenv: BNL, pmass, chrom, tune and bunch_charge
# but first make backups for testing and for safety
for myenv in .. `ls studies`
do
  cp studies/$myenv/sixdeskenv studies/$myenv/sixdeskenv.beforeupdate
  cp studies/$myenv/sysenv studies/$myenv/sysenv.beforeupdate
done

for myenv in .. `ls studies`
do
  grep pmass studies/$myenv/sixdeskenv > /dev/null 2>&1
  if test $? -ne 0
  then
    sed -fscripts/sedpmass studies/$myenv/sixdeskenv > tmp$$
    if test $? -ne 0
    then
      echo "ERROR!!!"
      exit
    else
      mv tmp$$ studies/$myenv/sixdeskenv
    fi
  fi
done
for myenv in .. `ls studies`
do
  grep "chrom_eps=" studies/$myenv/sixdeskenv > /dev/null 2>&1
  if test $? -ne 0
  then
    sed -fscripts/sedchrom studies/$myenv/sixdeskenv > tmp$$
    if test $? -ne 0
    then
      echo "ERROR!!!"
      exit
    else
      mv tmp$$ studies/$myenv/sixdeskenv
    fi
  fi
done
for myenv in .. `ls studies`
do
  grep "tune=" studies/$myenv/sixdeskenv > /dev/null 2>&1
  if test $? -ne 0
  then
    sed -fscripts/sedtune studies/$myenv/sixdeskenv > tmp$$
    if test $? -ne 0
    then
      echo "ERROR!!!"
      exit
    else
      mv tmp$$ studies/$myenv/sixdeskenv
    fi
  fi
done
for myenv in .. `ls studies`
do
  grep bunch_charge studies/$myenv/sixdeskenv > /dev/null 2>&1
  if test $? -ne 0
  then
    sed -fscripts/sedbunch_charge studies/$myenv/sixdeskenv > tmp$$
    if test $? -ne 0
    then
      echo "ERROR!!!"
      exit
    else
      mv tmp$$ studies/$myenv/sixdeskenv
    fi
  fi
done

# sysenv: exe versions and log, cronlog
for myenv in .. `ls studies`
do
  grep "sixdesklogdir=" studies/$myenv/sysenv > /dev/null 2>&1
  if test $? -ne 0
  then
    sed -fscripts/sedlog studies/$myenv/sysenv > tmp$$
    if test $? -ne 0
    then
      echo "ERROR!!!"
      exit
    else
      mv tmp$$ studies/$myenv/sysenv
# and make sure we have the directories (for an old study...)
      . ./studies/$myenv/sixdeskenv
      . ./studies/$myenv/sysenv
      mkdir -p $sixdesklogdir
      touch $sixdesklogdir/sixdesk.log
    fi
  fi
done
for myenv in .. `ls studies`
do
  grep "cronlogdir=" studies/$myenv/sysenv > /dev/null 2>&1
  if test $? -ne 0
  then
    sed -fscripts/sedcron studies/$myenv/sysenv > tmp$$
    if test $? -ne 0
    then
      echo "ERROR!!!"
      exit
    else
      mv tmp$$ studies/$myenv/sysenv
# and make sure we have the directories (for an old study...)
      . ./studies/$myenv/sixdeskenv
      . ./studies/$myenv/sysenv
      mkdir -p $cronlogdir
      touch $cronlogdir/cron_results.log
    fi
  fi
done

for myenv in .. `ls studies`
do
  grep "BNL=" studies/$myenv/sixdeskenv > /dev/null 2>&1
  if test $? -ne 0
  then
    sed -fscripts/sedbnl studies/$myenv/sixdeskenv > tmp$$
    if test $? -ne 0
    then
      echo "ERROR!!!"
      exit
    else
      mv tmp$$ studies/$myenv/sixdeskenv
    fi
  fi
done

# and ALWAYS append the new .exe anyway, all of them
for myenv in .. `ls studies`
do
  sed -fscripts/sedexes studies/$myenv/sysenv > tmp$$
  if test $? -ne 0
  then
    echo "ERROR!!!"
    exit
  else
    mv tmp$$ studies/$myenv/sysenv
  fi
done
