#!/bin/bash

############################## SCAN OVER A CARTESIAN GRID ######################

# specify the variable names to be used in naming the studies, e.g.:
# scan_variables="QP IOCT"
scan_variables="QP IOCT"

# specify the placeholders in the mask file, e.g.:
# scan_placeholders="%QPV %OCV"
scan_placeholders="%QPV %OCV"

# specify the prefix of the study name
# e.g. if the base mask file is called hl13B1.mask, we use:
# scan_prefix="hl10BaseB1"
scan_prefix="hl10BaseB1"

# specify the values to be taken by the different variables
# if we want to use 14 for QP and values between 0 and 40 in steps of 40 for IOCT:
# scan_vals_QP="3"
# scan_vals_IOCT=$(seq -500 200 500)
scan_vals_QP="3"
scan_vals_IOCT=$(seq -500 200 500)


############################## SCAN OVER SPECIFIC MASKS  #######################

# THIS OPTION REQUIRES ALL THE MASK FILES TO BE EXISTING

# (de)activate the scan over specific masks
scan_masks=false
scan_studies="
ats2017_QP_0_IOCT_12
ats2017_QP_0_IOCT_16
"
