# A.Mereghetti, 2017-03-07
# htcondor sub file for LSF-like jobs
universe = vanilla
# executable, completed by run_six.sh
executable = 
arguments = "$(dirname)"
output = $(dirname)htcondor.out
error = $(dirname)htcondor.err
log = $(Cluster).log
# do not ask htcondor to take care of output files, otherwise empty ones will be created while the simulation proceeds
transfer_output_files = ""
ShouldTransferFiles = YES
WhenToTransferOutput = ON_EXIT_OR_EVICT
SendCredential = True
queue dirname from
