#!/bin/sh
# Checks workspace for ONLY the current study
mychecklocksub()
{
  if test -d "$locks"
  then
    if test -f "$locks"/sixdesklock
    then
      if test ! -w "$locks"/sixdesklock
      then
        echo "The directory "$locks" is locked by the script"
        echo " `cat "$locks"/sixdesklock`"
       fi
    fi
  fi
}
# First test in case the studies directory is locked!
# Making sure we are in sixjobs.
export sixdeskroot=`basename $PWD`
if test "$sixdeskroot" != "sixjobs"
then
  echo "This script must be run in the directory sixjobs!!!"
  exit 1
fi
if test -d "studies"
then
  if test -f studies/sixdesklock
  then
    if test ! -w studies/sixdesklock
    then
      echo "The directory studies is locked by the script"
      echo " `cat studies/sixdesklock`"
      echo "We cannot continue checking until it is unlocked!!!"
      exit 3
    fi
  fi
else
  echo "The directory studies does not exist!!!"
  exit 2
fi
. ./dot_env
for locks in . .. ./plot sixdeskTaskIds $sixdeskstudy $sixtrack_input $sixdeskwork 
do
  echo "Checking $locks"
  mychecklocksub
done
for myplat in boinc cpss lsf
do
  for dir in ${myplat}jobs
  do
    locks=$sixdeskwork/$dir
    mychecklocksub
    locks=$sixdeskwork/$dir/jobs_logs
    mychecklocksub
  done
done

#MACRO myexit 0
sixdeskexitparam=0
sixdeskexit
#MACRO myexit

