#!/bin/sh
# expects workspace for comparison
if test $# -eq 0
then
  echo "Please give a workspace for comparison!!!"
  exit 1
fi
for scr in allmyseds `ls sed*`
do
  echo "================="
  echo "$scr"
  echo "================="
  diff $scr $1/sixjobs/scripts/$scr
done
