#!/bin/sh
#
# Create the AFS protection group sixdeskboinc
# owned by mcintosh (later to be owwned by AFS SI Group Admin)
# containing all users in u_slap
# The parameter sixdeskpts is defined is sysenv
# pts creategroup -name mcintosh:boinc -owner mcintosh

# Now changed to use the groupo boinc:users owned by boinc_admins
# with Mcintosh, pete, nils, boincadm, boinc, giovanno
#
# and now added all the existing users from mcintosh:boinc.
for myname in \
  zwe\
  mcintosh\
  dschulte\
  tpieloni\
  jowett\
  riss\
  frs\
  rtomas\
  stefano\
  yannis\
  koschik\
  grumolo\
  lombarda\
  robertde\
  udorda\
  rdemaria\
  ebenedet\
  bruening\
  jbarranc\
  giovanno\
  kaltchev\
  elaface\
  miwang\
  sfar\
  frankz\
  bholzer\
  xbuffat\
  ynosochk
do
 phonebook --terse login --login $myname
 if test $? -ne 0
 then
   echo "User $myname does NOT appear in the phonebook!"
 else
  echo "Adding $myname to boinc:users"
  pts adduser -group boinc:users -user $myname 
 fi
done
# and verify
pts membership -name boinc:users
