#!/bin/sh
# Special because we may have a parameter
# but we now insist it must be the THIRD.
# run_query / run_query STUDY / run_query STUDY PLATFORM /
# run_query STUDY PLATFORM RUNNAM
# No locks are held (except by dot_env itself).
. ./dot_env
cases=0
if test -f $sixdeskwork/taskids
then
  cases=`wc -l "$sixdeskwork/taskids"`
  cases=`echo "$cases" | sed -e 's? *\([0-9]*\).*?\1?'`
fi
icases=0
if test -s $sixdeskwork/incomplete_cases
then
  icases=`wc -l $sixdeskwork/incomplete_cases`
  icases=`echo $icases | sed -e 's? *\([0-9]*\).*?\1?'`
fi
ccases=0
if test -s $sixdeskwork/completed_cases
then
  ccases=`wc -l $sixdeskwork/completed_cases`
  ccases=`echo $ccases | sed -e 's? *\([0-9]*\).*?\1?'`
fi
mymess 0 "Found $cases cases, $ccases complete ($icases incomplete)"
if test $# -lt 3
then
  for myplatform in lsf boinc cpss grid
  do
    myname=tasks
    if test "$myplatform" = "lsf"
    then
      myname=jobs
    fi
    sixdeskjobs=$sixdeskwork/$myplatform"jobs"
    if test -s "$sixdeskjobs/$myname"
    then
      lsfjobs=`wc -l "$sixdeskjobs/$myname"`
      lsfjobs=`echo "$lsfjobs" | sed -e 's? *\([0-9]*\).*?\1?'`
      ijobs=0
      if test -s $sixdeskjobs/incomplete_$myname
      then
        ijobs=`wc -l $sixdeskjobs/incomplete_$myname`
        ijobs=`echo "$ijobs" | sed -e 's? *\([0-9]*\).*?\1?'`
      fi
      cjobs=0
      if test -s $sixdeskjobs/completed_$myname
      then
        cjobs=`wc -l $sixdeskjobs/completed_$myname`
        cjobs=`echo "$cjobs" | sed -e 's? *\([0-9]*\).*?\1?'`
      fi
      mjobs=0
      if test -s $sixdeskjobs/missing_$myname
      then
        mjobs=`wc -l $sixdeskjobs/missing_$myname`
        mjobs=`echo "$mjobs" | sed -e 's? *\([0-9]*\).*?\1?'`
      fi
      mymess 0 "For $myplatform found $lsfjobs $myname, $ijobs incomplete, $cjobs completed, $mjobs missing"
    fi
  done
else
  # we should have a Runnam
  Runnam=$3
  taskid=""
  found=""
  found=`grep '^'$Runnam' ' $sixdeskwork/taskids`
  if test "$found" != ""
  then
    taskids=`echo "$found" | cut -d" " -f2-`
    Runnam=`echo $found | cut -d" " -f1`
    myrundir $Runnam Rundir
    mymess 0 "Case $Runnam with $taskids found in $Rundir"
    where=$sixdesktrack/$Rundir
    if test ! -d "$where"
    then
      mymess 0 "Strange the directory $where for job $taskid does NOT exist!!! We shall ignore this for the moment"
    else
      if test -s "$where/fort.10.gz"
      then
        mymess 0 "Case complete $Runnam with taskids $taskids"
      else
        mymess 0 "Case incomplete $Runnam with taskids $taskids"
      fi
    fi
  else
     mymess 0 "Could not find Runnam $3"
  fi
fi
rm -f $tmp
myexit 0
