#!/bin/sh
#
. ./dot_env

#MACRO mymess 0 Checking Study $LHCDescrip in Workspace $workspace
sixdeskmesslevel=0
sixdeskmess="Checking Study $LHCDescrip in Workspace $workspace"
sixdeskmess
#MACRO mymess


#MACRO mymess 0 On `hostname`, Platform $platform
sixdeskmesslevel=0
sixdeskmess="On `hostname`, Platform $platform"
sixdeskmess
#MACRO mymess

if test "$BNL" != ""
then
  echo "=============="
  echo "== BNL env  =="
  echo "=============="
  echo "sixdeskplatform=$sixdeskplatform"
  echo "SIXTRACKBNLEXE=$SIXTRACKBNLEXE"
  echo "bnlseeds=$bnlseeds"
  echo "bnlseede=$bnlseede"
  echo "bnlsamples=$bnlsamples"
  echo "bnlsamplee=$bnlsamplee"
  echo "bnlpairs=$bnlpairs"
  echo "bnlperjob=$bnlperjob"
  echo "bnlturns=$bnlturns"
  echo "bnlturnse=$bnlturnse"
  echo "bnlwrite=$bnlwrite"

  echo "sixdeskbnlin=$sixdeskbnlin"
  echo "sixdeskbnlout=$sixdeskbnlout"
  echo "bnlfilenames=$bnlfilenames"
  echo "bnlfortnames=$bnlfortnames"
else
  echo "=============="
  echo "= sixdeskenv ="
  echo "=============="
  echo "istamad=$istamad"
  echo "iendmad=$iendmad"
  echo "runtype=$runtype"
  echo "sixdeskpairs=$sixdeskpairs"
  echo "ista=$ista"
  echo "iend=$iend"
  echo "kstep=$kstep"
  echo "long=$long"
  echo "ns1l=$ns1l"
  echo "ns2l=$ns2l"
  echo "nsincl=$nsincl"
  echo "turnsl=$turnsl"
  echo "turnsle=$turnsle"
  echo "writebinl=$writebinl"
  echo "kinil=$kinil"
  echo "kendl=$kendl"
  echo "kmaxl=$kmaxl"
  echo "iplot=$iplot"
  echo "kvar=$kvar"
fi
echo "=========="
echo "= sysenv ="
echo "=========="
echo "sixdeskcastor=$sixdeskcastor"
echo "boincdir=$boincdir"
echo "sixdeskboincname=$sixdeskboincname"
echo "sixdeskboinctest=$sixdeskboinctest"
echo "sixdeskboincdir=$sixdeskboincdir"
echo "MADX_PATH=$MADX_PATH"
echo "MADX=$MADX"
echo "SIXTRACKEXE=$SIXTRACKEXE"
echo "SIXTRACKDAEXE=$SIXTRACKDAEXE"
echo "sixdeskexec=$sixdeskexec"
echo "sixdeskTaskGroupName=$sixdeskTaskGroupName"

#MACRO myexit 0
sixdeskexitparam=0
sixdeskexit
#MACRO myexit

