#!/bin/sh
#lf95 --o1 --tp -Wa,--32 -o verify10 -static -m32 verify10.f
lf95 --o1 --tp -Wa,--32 -o verify10 -static -m32 -L/usr/lib/ -lc -L/usr/lib/gcc/x86_64-redhat-linux/3.4.6/32 -lgcc_eh verify10.f
