#!/bin/sh
# Create a dumpimg ground for results_6 files
# Works only for mcintosh
# boinc:users rl
# boinc:admins rlidwka
# boincsrv rlidwk
# mcintosh:boinc rlidwka
# system:administrators rlidwka
# system:anyuser rl
# mcintosh rlidwka
# boinc rlidwka

mkdir -p $WORK/results_6
fs setacl $WORK/results_6 boinc:users rl
fs setacl $WORK/results_6 boinc:admins rlidwka
fs setacl $WORK/results_6  boincsrv rlidwk
fs setacl $WORK/results_6  mcintosh:boinc rlidwka
fs setacl $WORK/results_6  system:administrators rlidwka
fs setacl $WORK/results_6  system:anyuser rl
fs setacl $WORK/results_6  mcintosh rlidwka
fs setacl $WORK/results_6  boinc rlidwka
