#!/bin/ksh
#
# This script should be run before run_bnl which submits
# the jobs or tasks or workunits
# sixdeskenv (sysenv) should have been edited and
# the files beambeamdist.dat, fort.2, fort.3.mother,
# fort.8, and fort.16 put in the directory (link) sixtrack_input
. ./dot_env
if test "$BNL" = ""
then

#MACRO mymess 0 Something up!! prepare_bnl expects BNL $BNL
  sixdeskmesslevel=0
  sixdeskmess="Something up!! prepare_bnl expects BNL $BNL"
  sixdeskmess
#MACRO mymess
 to be set
fi
dir16=$sixtrack_input

#MACRO mymess 1 Using sixtrack_input $dir16
sixdeskmesslevel=1
sixdeskmess="Using sixtrack_input $dir16"
sixdeskmess
#MACRO mymess

if test ! -d "$dir16" 
then

#MACRO mymess 0 The directory $dir16 does not exist!!!
  sixdeskmesslevel=0
  sixdeskmess="The directory $dir16 does not exist!!!"
  sixdeskmess
#MACRO mymess
 

#MACRO myexit 1
  sixdeskexitparam=1
  sixdeskexit
#MACRO myexit

fi

#MACRO mylock $sixtrack_input
sixdesklockdir=$sixtrack_input
sixdesklock
#MACRO mylock

#
if test "$bnlsamplee" -lt "$bnlsamples"
then

#MACRO mymess 0 A negative number of samples requested!!!
  sixdeskmesslevel=0
  sixdeskmess="A negative number of samples requested!!!"
  sixdeskmess
#MACRO mymess


#MACRO mymess 0 Please check bnlsamples/bnlsamplee $bnlsamples/$bnlsamplee
  sixdeskmesslevel=0
  sixdeskmess="Please check bnlsamples/bnlsamplee $bnlsamples/$bnlsamplee"
  sixdeskmess
#MACRO mymess


#MACRO myexit 2
  sixdeskexitparam=2
  sixdeskexit
#MACRO myexit

fi
tree=$sixdesktrack
if [ ! -d "$tree/$LHCDesHome" ] ;then
  mkdir -p $tree/$LHCDesHome
fi
# set up of beambeamdist.dat (fort.54) for all defined cases
# main loop

#MACRO mymess 1 Main loop for Study $LHCDescrip, Seeds $bnlseeds to $bnlseede
sixdeskmesslevel=1
sixdeskmess="Main loop for Study $LHCDescrip, Seeds $bnlseeds to $bnlseede"
sixdeskmess
#MACRO mymess


#MACRO mymess 1 and Samples $bnlsamples to $bnlsamplee
sixdeskmesslevel=1
sixdeskmess="and Samples $bnlsamples to $bnlsamplee"
sixdeskmess
#MACRO mymess

bnlseed=$bnlseeds
if test ! -d $sixtrack_input/$bnlseed
then

#MACRO mymess 0 The directory $sixtrack_input/$bnlseed does NOT exist!!!
  sixdeskmesslevel=0
  sixdeskmess="The directory $sixtrack_input/$bnlseed does NOT exist!!!"
  sixdeskmess
#MACRO mymess


#MACRO myunlock $sixtrack_input
  sixdesklockdir=$sixtrack_input
  sixdeskunlock
#MACRO myunlock


#MACRO myexit 3
  sixdeskexitparam=3
  sixdeskexit
#MACRO myexit

fi
while test "$bnlseed" -le "$bnlseede"
do
  if test ! -f $sixtrack_input/"$bnlseed"/"beambeamdist.dat"
  then

#MACRO mymess 0 Seed $bnlseed/beambeamdist.dat is missing!!!
    sixdeskmesslevel=0
    sixdeskmess="Seed $bnlseed/beambeamdist.dat is missing!!!"
    sixdeskmess
#MACRO mymess


#MACRO myunlock $sixtrack_input
    sixdesklockdir=$sixtrack_input
    sixdeskunlock
#MACRO myunlock


#MACRO myexit 4
    sixdeskexitparam=4
    sixdeskexit
#MACRO myexit

  fi
  bnlsample=$bnlsamples
  bnlpair1=1
  i=0
  while read line
  do
    bnlpair2=`expr $bnlpair1 + $bnlperjob`
    bnlpair2=`expr $bnlpair2 - 1`
    bnlpair=$bnlpair1"_"$bnlpair2
    bnlperjob2=`expr $bnlperjob \* 2`
    if test "$i" -eq 0
    then
      Runnam=$LHCDesName"%"$bnlseed"%"$bnlsample"%"$bnlpair"%"$bnlturnse
      Rundir=$LHCDesName/$bnlseed/$bnlsample/$bnlpair/$bnlturnse

#MACRO mymess 2 Setting up Rundir $Rundir
      sixdeskmesslevel=2
      sixdeskmess="Setting up Rundir $Rundir"
      sixdeskmess
#MACRO mymess

      mkdir -p "$tree"/"$Rundir"
      # setup the (shorter) beambeamdist.dat and the fort.54 link
      rm -rf $tree"/"$Rundir"/"$sixdeskbnlin".gz"
    fi
    echo "$line" >> $tree"/"$Rundir"/"$sixdeskbnlin
    i=`expr $i + 1`
    if test "$i" -eq "$bnlperjob2"
    then
      i=0
      gzip -f $tree"/"$Rundir"/"$sixdeskbnlin
      ln -sf $tree"/"$Rundir"/"$sixdeskbnlin".gz" $tree"/"$Rundir/beambeamdist.dat.gz
      bnlpair1=`expr $bnlpair1 + $bnlperjob`
    fi
    if test "$bnlpair1" -gt "$bnlpairs"
    then
      bnlpair1=1
      bnlsample=`expr $bnlsample + 1`
    fi
  done < $sixtrack_input/"$bnlseed"/"beambeamdist.dat"
  if test "$bnlsample" -le "$bnlsamplee"
  then

#MACRO mymess 0 End beambeamdist.dat, there is NO sample $bnlsample!!!
    sixdeskmesslevel=0
    sixdeskmess="End beambeamdist.dat, there is NO sample $bnlsample!!!"
    sixdeskmess
#MACRO mymess

  fi
  bnlseed=`expr $bnlseed + 1`
done

#MACRO myunlock $sixtrack_input
sixdesklockdir=$sixtrack_input
sixdeskunlock
#MACRO myunlock


#MACRO myexit 0
sixdeskexitparam=0
sixdeskexit
#MACRO myexit

