#!/bin/sh
#
if test $# -ne 3
then
  echo "Please specify a workspace a study and a platform!"
  exit 1
fi
WS=$1
STUDY=$2
PLATFORM=$3
sed -e 's/%WS%/'$WS'/g' \
    -e 's/%STUDY%/'$STUDY'/g' \
    -e 's/%PLATFORM%/'$PLATFORM'/g' \
       run_template > run_batch$$
chmod 755 run_batch$$
bsub -q1nd run_batch$$
