#!/bin/sh
#
if test $# -ne 3
then
  echo "Please specify a workspace a study and a platform!"
  exit 1
fi
WS=$1
STUDY=$2
PLATFORM=$3
sed -e 's/%WS%/'$WS'/g' \
    -e 's/%STUDY%/'$STUDY'/g' \
    -e 's/%PLATFORM%/'$PLATFORM'/g' \
       join10_template > join10_batch$$
chmod 755 join10_batch$$
bsub -q1nd join10_batch$$
