#!/bin/sh
#
# Should be in run in the directory sixjobs
# Requires name of new workspace as $1
# Optional LOGNAME as $2
# Compares only scripts for the moment
#
if test $# -eq 0
then
  echo "Please specify name of new workspace for comparison"
  exit 1
fi
new=$1
if test $# -eq 2
then
  uname=$2
else
  uname=$LOGNAME
fi
initial=`echo $uname | cut -c 1`
mybdir=/afs/cern.ch/user/$initial/$uname
###for fnordir in `ls scripts/my*`
cd scripts
for fnordir in `ls`
do
  if test -d $fnordir
  then
    echo "====================="
    echo "$fnordir (directory)"
    echo "====================="
    cd $fnordir
    for fn in `ls`
    do
      echo "====================="
      echo "$fn"
      diff -r --report $fn $mybdir/$new/sixjobs/scripts/$fnordir/$fn
    done
    cd -
  else
    echo "====================="
    echo "$fnordir"
    diff --report $fnordir $mybdir/$new/sixjobs/scripts/$fnordir
  fi
done
