#!/bin/sh
#
# This script will (re-)submit a case if its status is incomplete 
# and it will submit to LSF for a BOINC study with results returned
# to the BOINC buffer
. ./dot_env
if test $sixdeskplatform != "boinc"
then
  echo "This command is intended to run incomplete cases"
  echo "on LSF in order to finish a BOINC study!!!"

#MACRO myexit 98
  sixdeskexitparam=98
  sixdeskexit
#MACRO myexit

fi

#MACRO mylock $sixdeskstudy
sixdesklockdir=$sixdeskstudy
sixdesklock
#MACRO mylock

mkdir -p $sixdeskjobs

#MACRO mymktmp copy $sixdeskjobs
sixdesktmpname=copy
sixdesktmpdirarg=$sixdeskjobs
sixdeskmktmp
copy=$sixdesktmp
#MACRO mymktmp

cp $sixdeskwork/incomplete_cases $copy
while read line
do
  export sixdeskRunnam=`echo $line | cut -d" " -f1`
  entry=`grep "$sixdeskRunnam " $sixdeskwork/taskids`
  if test "$entry" = ""
  then

#MACRO mymess 0 Something badly wrong!!! We cannot find $sixdeskRunnam in $sixdeskwork/taskids
    sixdeskmesslevel=0
    sixdeskmess="Something badly wrong!!! We cannot find $sixdeskRunnam in $sixdeskwork/taskids"
    sixdeskmess
#MACRO mymess


#MACRO myunlock $sixdeskstudy
    sixdesklockdir=$sixdeskstudy
    sixdeskunlock
#MACRO myunlock


#MACRO myexit 1
    sixdeskexitparam=1
    sixdeskexit
#MACRO myexit

  fi

#MACRO myrundir $sixdeskRunnam sixdeskRundir
  runnamename=$sixdeskRunnam
  sixdeskrundir
  sixdeskRundir=$rundirname
#MACRO myrundir

  export sixdeskRundir
  where=$sixdesktrack/$sixdeskRundir
  taskids=`echo $entry | cut -d" " -f2-`
  if test ! -d "$where"
  then

#MACRO mymess 0 The directory $sixdeskRundir for job $sixdeskRunnam does NOT exist!!!
    sixdeskmesslevel=0
    sixdeskmess="The directory $sixdeskRundir for job $sixdeskRunnam does NOT exist!!!"
    sixdeskmess
#MACRO mymess


#MACRO myunlock $sixdeskstudy
    sixdesklockdir=$sixdeskstudy
    sixdeskunlock
#MACRO myunlock


#MACRO myexit 2
    sixdeskexitparam=2
    sixdeskexit
#MACRO myexit

  fi
  if test ! -s "$where/fort.10.gz" -o $sixdeskforce -ge 2
  then

#MACRO mymess 1 Job incomplete $taskids for $sixdeskRunnam
    sixdeskmesslevel=1
    sixdeskmess="Job incomplete $taskids for $sixdeskRunnam"
    sixdeskmess
#MACRO mymess

    if test $sixdeskforce -eq 0
    then
      export sixdeskforce=1 
    fi
# Now do we need to define anything else for this call????
    export lsfjobtype=sixtrackingboinc
    . ./dot_boinclsf
    stat=$?
    if test "$stat" -ne 0
    then

#MACRO mymess 0 dot_boinclsf failed!!!
      sixdeskmesslevel=0
      sixdeskmess="dot_boinclsf failed!!!"
      sixdeskmess
#MACRO mymess


#MACRO myexit 99
      sixdeskexitparam=99
      sixdeskexit
#MACRO myexit

    fi
  fi
done < $copy
rm $copy

#MACRO myunlock $sixdeskstudy
sixdesklockdir=$sixdeskstudy
sixdeskunlock
#MACRO myunlock


#MACRO mymess 0 Completed normally
sixdeskmesslevel=0
sixdeskmess="Completed normally"
sixdeskmess
#MACRO mymess


#MACRO myexit 0
sixdeskexitparam=0
sixdeskexit
#MACRO myexit

