#!/bin/sh
# Checks all locks in workspace
mychecklocksub()
{
# echo "Using lockfile $locks" 
  if test -d "$locks"
  then
    if test -f "$locks"/sixdesklock
    then
      if test ! -w "$locks"/sixdesklock
      then
        echo "The directory "$locks" is locked by the script"
        echo " `cat "$locks"/sixdesklock`"
       fi
    fi
  fi
}
# First test in case the studies directory is locked!
# Making sure we are in sixjobs and dot_profile exists.
export sixdeskroot=`basename $PWD`
if test "$sixdeskroot" != "sixjobs"
then
  echo "This script must be run in the directory sixjobs!!!"
  exit 1
fi
if test ! -s dot_profile
then
  echo "The script dot_profile appears to be missing!!!"
  exit 4 
fi
. ./dot_profile
if test ! -d "studies"
then
  echo "The directory studies does not exist!!!"
  exit 2
fi
# first check sixjobs workspace plot sixdeskTaskIds (common to all studies)
echo "Checking sixjobs"
  locks="." 
  mychecklocksub
echo "Checking workspace"
  locks=".." 
  mychecklocksub
echo "Checking plot"
  locks="./plot" 
  mychecklocksub
echo "Checking sixdeskTaskIds"
  locks="./sixdeskTaskIds" 
  mychecklocksub
# Now check all studies

#MACRO mymktmp tmp /tmp
sixdesktmpname=tmp
sixdesktmpdirarg=/tmp
sixdeskmktmp
tmp=$sixdesktmp
#MACRO mymktmp


#MACRO mymktmp tmp2 /tmp
sixdesktmpname=tmp2
sixdesktmpdirarg=/tmp
sixdeskmktmp
tmp2=$sixdesktmp
#MACRO mymktmp

#echo "check_all_locks using $tmp $tmp2"
ls -tr studies > $tmp
while read myitem
do
  if test -d studies/"$myitem"
  then
    echo "$myitem" >> $tmp2
  fi
done < $tmp
rm $tmp
while read mystudy
do
  echo "Checking Study $mystudy"
  locks=studies/$mystudy
  mychecklocksub
  locks=$sixdesk_input/../$mystudy
  mychecklocksub
  locks=$sixdesktrack/../$mystudy
  mychecklocksub
  locks=$sixdeskwork/../$mystudy
  mychecklocksub
  for myplat in boinc cpss lsf
  do
    for dir in ${myplat}jobs
    do
      locks=$sixdeskwork/../$mystudy/$dir
      mychecklocksub
      locks=$sixdeskwork/../$mystudy/$dir/jobs_logs
      mychecklocksub
    done
  done
done < $tmp2
rm $tmp2
exit 0
