#!/bin/sh
for i in `ls`
do
  echo "======================="
  echo "$i"
  echo "======================="
#  diff $i ~/w27may09/sixjobs/scripts/$i
#  diff ~/w10mar09pro/sixjobs/scripts/$i $i
#  diff ~tpieloni/w1/sixjobs/scripts/$i $i
#   diff $i ~/w3march10/sixjobs/scripts/$i
#  diff $i ~giovanno//w3/sixjobs/scripts/$i
   diff $i ~/wbnlaug10/sixjobs/scripts/$i
done
