#!/bin/sh
#
# This script will submit a task 
# using the $1 sixdeskRunnam and the $2 directory sixdeskRundir
# $3=0 mean submit only if not submitted already
# $3=1 means (re-)submit anyway
# The task is NEVER submitted if fort.10.gz exists
# The sixdeskRundir is relative to $sixdesktrack
# It then creates or updates the taskids file to include the new taskid
# The variables sixdeskRunam sixdeskRundir and sixdeskforce must
# be set before calling by . ./dot_boinc
myrundir $sixdeskRunnam sixdeskRundir
if test ! -d $sixdeskboincdir
then
  mkdir -p $sixdeskboincdir
  # and here use AFS protection group stuff to fix access control list
  fs setacl $sixdeskboincdir $LOGNAME rlidwka
  fs setacl $sixdeskboincdir $sixdeskpts rl
fi
if test -s $sixdeskboincdir/owner
then
  sixdeskowner=`cat $sixdeskboincdir/owner`
  if test "$sixdeskowner" != "$LOGNAME"
  then
    mymess 0 "The workspace/LHCDescrip $sixdeskboincdirname are already in use by $sixdeskowner!!!"
    myexit 11
  fi
else
  echo "$LOGNAME" > $sixdeskboincdir/owner
fi
# and here use AFS protection group stuff to fix access control list
fs setacl $sixdeskboincdir $LOGNAME rlidwka
fs setacl $sixdeskboincdir $sixdeskpts rl
mkdir -p $sixdeskboincdir/work
mkdir -p $sixdeskboincdir/results
# and now try and run faster using a different sixdeskTaskId 
# for each study
if test  ! -d $sixdeskhome/sixdeskTaskIds/$LHCDescrip
then
  mkdir -p $sixdeskhome/sixdeskTaskIds/$LHCDescrip
  echo "0" > $sixdeskhome/sixdeskTaskIds/$LHCDescrip/sixdeskTaskId
fi
SIXDESKWHERE=$sixdesktrack/$sixdeskRundir
echo "sixdeskRunnam $sixdeskRunnam SIXDESKWHERE $SIXDESKWHERE FORCE $sixdeskforce sixdeskboincdir  $sixdeskboincdir"
if test ! -d $SIXDESKWHERE
then
  mymess 0 "$SIXDESKWHERE is NOT a directory!!!" 
  myexit 5
fi
sixdeskrunit="true"
if test -s $SIXDESKWHERE/fort.10.gz -a "$sixdeskforce" -lt 2
then
  mymess 1 "Task $sixdeskRunnam already completed; we will NOT re-submit"
  sixdeskrunit="false"
else
  if test "$sixdeskforce" -eq 0
  then
    ###mylock $sixdeskwork
    if test -s $sixdeskwork/taskids
    then
      grep "$sixdeskRunnam " $sixdeskwork/taskids > /dev/null 2>&1
      sixdeskstat=$?
      if test $sixdeskstat -eq 0
      then
        line=`grep "$sixdeskRunnam " $sixdeskwork/taskids`
        sixdeskoldtaskid=`echo $line | cut -d " " -f2-`
        if test "$sixdeskoldtaskid" != ""
        then
          mymess 1 "Task $sixdeskRunnam already submitted taskid(s) $sixdeskoldtaskid; skipping it"
          sixdeskrunit="false"
        fi
      fi 
    fi
    ###myunlock $sixdeskwork
  fi
fi
if test $sixdeskrunit = "true"
then
  mymktmp tmp
  mkdir -p $sixdeskjobs_logs/run
  # We are going to (re-)submit it
  sixdeskexists=0
  for sixdeski in 2 3 8 16
  do
    if test ! -f $SIXDESKWHERE/fort.$sixdeski.gz
    then
      mymess 0 "File $SIXDESKWHERE/fort.$sixdeski.gz does NOT exist!!!"
    else
      sixdeskexists=`expr $sixdeskexists + 1`
    fi
  done
  if test "$sixdeskexists" -ne 4
  then
    sixdeskexists=`expr 4 - $sixdeskexists`
    mymess 0 "There are $sixdeskexists input files missing!!! in $SIXDESKWHERE"
    mymess 0 "Skipping this case which will require a RUN_SIX!!!"
    rm -f $tmp
  else
    # Make sure we are clean (in case of a run_six or system crash)
    rm -f $sixdeskjobs_logs/run/fort.*
    for sixdeski in 2 3 8 16
    do
      cp $SIXDESKWHERE/fort.$sixdeski.gz $sixdeskjobs_logs/run
      gunzip -f $sixdeskjobs_logs/run/fort.$sixdeski.gz
    done
    sixdeskTaskName=$workspace"_"$sixdeskRunnam
    sixdeskTaskName=`echo $sixdeskTaskName | sed -e's?%?__?g'`
    sixdeskfileDir=$sixdeskjobs_logs/run
  # mylock $sixdeskhome/sixdeskTaskIds
    sixdeskTaskId=`cat $sixdeskhome/sixdeskTaskIds/$LHCDescrip/sixdeskTaskId`
    sixdeskTaskId=`expr $sixdeskTaskId + 1`
    echo $sixdeskTaskId > $sixdeskhome/sixdeskTaskIds/$LHCDescrip/sixdeskTaskId
  # myunlock $sixdeskhome/sixdeskTaskIds
    sixdesktaskid=boinc$sixdeskTaskId
    gotit=""
    mytries=0
    while test "$gotit" != "OK" -a $mytries -ne 11
    do
      mytries=`expr $mytries + 1`
###  $sixdeskpath/Bin/uploadWorkunit_many $sixdeskTaskName 1 sixvf $sixdeskjobs_logs/run $sixdesktaskid $sixdeskfpopse $sixdeskboincdir > $tmp 2>&1
     $sixdeskpath/Bin/uploadWorkunit $sixdeskTaskName 1 sixvf $sixdeskjobs_logs/run $sixdesktaskid $sixdeskfpopse $sixdeskboincdir > $tmp 2>&1
      sixdeskstat=$?
      if test $sixdeskstat -ne 0
      then
        mymess 0 "UploadWorkunit failed with Status $sixdeskstat !!! `cat $tmp`"
        rm $tmp
      else
        gotit="OK"
      fi
    done 
    rm $sixdeskjobs_logs/run/fort.2 $sixdeskjobs_logs/run/fort.3 $sixdeskjobs_logs/run/fort.8 $sixdeskjobs_logs/run/fort.16
    if test "$gotit" != "OK"
    then
      mymess 0 "FAILED to submit task 10 times!!"
      rm -f $tmp
      myexit 10
    fi
    if test ! -s $SIXDESKWHERE/fort.10.gz 
    then
      touch $SIXDESKWHERE/JOB_NOT_YET_COMPLETED
    fi
    ###mylock $sixdeskwork
    sixdeskoldtaskid=""
    if test -s $sixdeskwork/taskids
    then
      grep "$sixdeskRunnam " $sixdeskwork/taskids
      sixdeskstat=$?
      if test $sixdeskstat -eq 0
      then
        line=`grep "$sixdeskRunnam " $sixdeskwork/taskids`
        sixdeskoldtaskid=`echo $line | cut -d " " -f2-`
      fi
    fi
    if test "$sixdeskoldtaskid" = ""
    then
      sixdesktaskids=$sixdesktaskid" "
    else
      sixdesktaskids=$sixdeskoldtaskid" "$sixdesktaskid" "
    fi
    touch $SIXDESKWHERE/JOB_NOT_YET_COMPLETED
    if test -s $sixdeskwork/taskids
    then
      sed -e'/'$sixdeskRunnam' /d' $sixdeskwork/taskids > $tmp
      mv $tmp $sixdeskwork/taskids
    fi
    echo "$sixdeskRunnam" "$sixdesktaskids" >> $sixdeskwork/taskids
    if test "$sixdeskoldtaskid" != ""
    then
      mymess 1 "Task $sixdeskRunnam re-submitted with TaskId $sixdesktaskid; other tasks $sixdeskoldtaskid"
    else
      echo $sixdeskRunnam >> $sixdeskwork/incomplete_cases
      echo $sixdeskRunnam >> $sixdeskwork/myincomplete_cases
      mymess 1 "Task $sixdeskRunnam submitted with TaskId $sixdesktaskid"
    fi
    ###myunlock $sixdeskwork
    ###mylock $sixdeskjobs
    echo "$sixdeskRunnam" "$sixdesktaskid" >> $sixdeskjobs/tasks
    echo "$sixdeskRunnam" "$sixdesktaskid" >> $sixdeskjobs/incomplete_tasks
    ###myunlock $sixdeskjobs
    rm -f $tmp
  fi
fi
