#!/bin/sh
#
# This script will re-submit tasks
# It uses the taskids file to get relevant info
# Runnam Rundir (relative to $sixdeskdata)
. ./dot_env
if test $sixdeskplatform = "lsf"
then
  echo "This command is NOT available for LSF"
  myexit 98
fi
mylock $sixdeskstudy
mymktmp mytaskids
###mylock $sixdeskwork
cp $sixdeskwork/taskids $mytaskids 
###myunlock $sixdeskwork
while read line
do
  sixdeskRunnam=`echo $line | cut -d" " -f1`
  myrundir $sixdeskRunnam sixdeskRundir
  where=$sixdesktrack/$sixdeskRundir
  taskids=`echo $entry | cut -d" " -f2-`
  if test ! -d "$where"
  then
    mymess 0 "The directory $sixdeskRundir for job $sixdeskRunnam does NOT exist!!!"
    myexit 2
  fi
  export sixdeskforce=2 
  if test "$sixdeskplatform" = "cpss"
  then
    . ./dot_task
    stat=$?
  elif test "$sixdeskplatform" = "boinc"
  then
    . ./dot_boinc
    stat=$?
  elif test "$sixdeskplatform" = "grid"
  then
    . ./dot_grid
    stat=$?
  fi
  if test $stat -ne 0
  then
    mymess 0 "dot_task/dot_boinc/dot_grid failed!!!"
    myexit 99
  fi
done < $mytaskids
rm $mytaskids
myunlock $sixdeskstudy
myexit 0
