#!/bin/bash

# ------------------------------------------------------------------------------
# preliminary to any action
# ------------------------------------------------------------------------------
# - get path to calling script and normalise it
SCRIPTDIR=`dirname $0`
SCRIPTDIR="`cd "${SCRIPTDIR}";pwd`"
# ------------------------------------------------------------------------------


pdflatex "\newcommand{\filename}{"$1"} \input{"${SCRIPTDIR}/"DAsurv.tex}"
rm DAsurv.log DAsurv.aux
