#!/bin/bash
# Just do a run_status for all studies

# ------------------------------------------------------------------------------
# preliminary to any action
# ------------------------------------------------------------------------------
# - get path to calling script and normalise it
SCRIPTDIR=`dirname $0`
SCRIPTDIR="`cd "${SCRIPTDIR}";pwd`"
# ------------------------------------------------------------------------------

for mystudy in `ls studies`
do
  if test -d studies/"$mystudy"
  then
    echo ""
    ${SCRIPTDIR}/run_query "$mystudy"
  fi
done
