#!/bin/bash

# ------------------------------------------------------------------------------
# preliminary to any action
# ------------------------------------------------------------------------------
# - get path to scripts (normalised)
if [ -z "${SCRIPTDIR}" ] ; then
    SCRIPTDIR=`dirname $0`
    SCRIPTDIR="`cd ${SCRIPTDIR};pwd`"
    export SCRIPTDIR=`dirname ${SCRIPTDIR}`
fi
# ------------------------------------------------------------------------------


pdflatex "\newcommand{\filename}{"$1"} \input{"${SCRIPTDIR}/"tex/DAsurv.tex}"
rm DAsurv.log DAsurv.aux
