#!/bin/bash
#

# ------------------------------------------------------------------------------
# preliminary to any action
# ------------------------------------------------------------------------------
# - get path to scripts (normalised)
if [ -z "${SCRIPTDIR}" ] ; then
    SCRIPTDIR=`dirname $0`
    SCRIPTDIR="`cd ${SCRIPTDIR};pwd`"
    export SCRIPTDIR=`dirname ${SCRIPTDIR}`
fi
# ------------------------------------------------------------------------------

source ${SCRIPTDIR}/bash/dot_env

#MACRO mytunes
sixdesktunes
#MACRO mytunes

# And now we have a new loop over the tunescans
itunexx=$itunex
ituneyy=$ituney
while test "$itunexx" -le "$itunex1" -a "$ituneyy" -le "$ituney1"
do
  # returns sixdesktunes and tunexx/tuneyy, computed from itunexx/ituneyy,
  #    using xlen/ylen
  sixdeskPrepareTunes
  echo "Tunes $sixdesktunes"
  s=$istamad
  while test "$s" -le $iendmad
  do
    echo "Seed $s"
    cat $sixdesktrack/$LHCDescrip/$s/simul/$sixdesktunes/betavalues
    s=`expr $s + 1`
  done
  itunexx=`expr $itunexx + $ideltax`
  ituneyy=`expr $ituneyy + $ideltay`
done
