#!/bin/bash
# Just executes exec_env

# ------------------------------------------------------------------------------
# preliminary to any action
# ------------------------------------------------------------------------------
# - get path to calling script and normalise it
SCRIPTDIR=`dirname $0`
SCRIPTDIR="`cd "${SCRIPTDIR}";pwd`"
# ------------------------------------------------------------------------------

${SCRIPTDIR}/exec_env sixdeskenv sysenv
