#!/bin/bash
# Just do a run_status for all studies

# ------------------------------------------------------------------------------
# preliminary to any action
# ------------------------------------------------------------------------------
# - get path to scripts (normalised)
if [ -z "${SCRIPTDIR}" ] ; then
    SCRIPTDIR=`dirname $0`
    SCRIPTDIR="`cd ${SCRIPTDIR};pwd`"
    export SCRIPTDIR=`dirname ${SCRIPTDIR}`
fi
# ------------------------------------------------------------------------------

for mystudy in `ls studies`
do
  if test -d studies/"$mystudy"
  then
    echo ""
    ${SCRIPTDIR}/run_query "$mystudy"
  fi
done
